### ISSUE TITLE
Upgrade from 5.0.41~ynh2 to 6.0.4~ynh1 

### ISSUE THREAD

**Issue by rodinux** [YunoHost-Apps/zabbix_ynh#79]
### Describe the bug

*Upgrade brake bdd*

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.3.0.2
- I have access to my server: *Through SSH | through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using : 5.0.41~ynh2
- Try remove zabbix, install a fresh zabbix 6.0~ynh1
- import a dump db from 

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app upgrade zabbix
    sudo yunohost remove zabbix
    sudo yunohost install zabbix
   mysql -u root 
   DROP DATABASE zabbix; 
   CREATE DATABASE zabbix; 
   \q
   mysql -u root zabbix < db_backup_zabbix.sql
    ```

### Expected behavior

*Upgrade zabbix*

### Logs

Here the log of the upgrade fails
https://paste.yunohost.org/raw/uporuhayun

**Comment by rodinux** [comment]
It's more complicated

There was 2 dependencies, the app and system needs upgrade

```
apps:
  current_version: 5.0.41~ynh2
  description: Outil pour monitorer des réseaux, des serveurs, des VMs et autres services en ligne
  domain_path: y2.numc.eu/zabbix
  id: zabbix
  logo: 9b0729fce7e4d0cd7de448f702cf44bb528dc1e46596107cd68dcbe41dd5ae34
  name: Zabbix
  new_version: 6.0~ynh1
  notifications:
  upgradable: yes
  version: 5.0.41~ynh2

system:
  0:
    current_version: 1:5.0.45-1+debian11
    name: zabbix-agent
    new_version: 1:5.0.45+dfsg-1+deb11u1
  1:
    current_version: 1:5.0.45-1+debian11
    name: zabbix-frontend-php
    new_version: 1:5.0.45+dfsg-1+deb11u1
  2:
    current_version: 1:5.0.45-1+debian11
    name: zabbix-server-mysql
    new_version: 1:5.0.45+dfsg-1+deb11u1
```
I keep a dump of the db in case

If I upgrade the system it breaks zabbix connection ti the DB, we see a front-web page which want to enter DB credentials as in this post from forum https://forum.yunohost.org/t/mise-a-jour-du-paquet-zabbix/31022/13

So I have first try upgrade the app, but it fails because of the dependencies of the system... And can't restore for same reason... worse, the restore did not works, but the app was still in the list apps
So I first remove the app
`yunohost remove app zabbix`

I have try intall a fresh zabbix
`yunohost install zabbix`

then import the db from the 5.0.41~yh2
```
mysql -u root 
DROP DATABASE zabbix; 
CREATE DATABASE zabbix; 
\q
mysql -u root zabbix < db_backup_zabbix.sql
```
The error then was clear like in #44
> La version de la base de données Zabbix ne correspond pas aux exigences actuelles. Version de votre base de données : > 5000000. Version requise : 6000000. Veuillez contacter votre administrateur système.

There is a documentation here about migrating zabbix DB 
https://www.zabbix.com/documentation/6.4/fr/manual/appendix/install/db_primary_keys#important-notes

So I rollback
```
yunohost remove app zabbix
dpkg --list | grep zabbix
```
I must be sure no packages zabbix still here !
```
yunohost backup restore zabbix-pre-upgrade1
```

I am getting now as the beginning
```
apps:
  current_version: 5.0.41~ynh2
  description: Outil pour monitorer des réseaux, des serveurs, des VMs et autres services en ligne
  domain_path: y2.numc.eu/zabbix
  id: zabbix
  logo: 9b0729fce7e4d0cd7de448f702cf44bb528dc1e46596107cd68dcbe41dd5ae34
  name: Zabbix
  new_version: 6.0~ynh1
  notifications:
  upgradable: yes
  version: 5.0.41~ynh2

system:
  0:
    current_version: 1:5.0.45-1+debian11
    name: zabbix-agent
    new_version: 1:5.0.45+dfsg-1+deb11u1
  1:
    current_version: 1:5.0.45-1+debian11
    name: zabbix-frontend-php
    new_version: 1:5.0.45+dfsg-1+deb11u1
  2:
    current_version: 1:5.0.45-1+debian11
    name: zabbix-server-mysql
    new_version: 1:5.0.45+dfsg-1+deb11u1
```
